import fs from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { expect, test } from '@playwright/test';
import { createRsbuild } from '@rsbuild/core';
import { pluginLess } from '@rsbuild/plugin-less';
import { pluginSass } from '@rsbuild/plugin-sass';
import { pluginTypedCSSModules } from '../../dist';
import { generatorTempDir } from '../helper';

const __dirname = dirname(fileURLToPath(import.meta.url));

test('generator TS declaration for multiple Less or Sass plugins', async () => {
  const testDir = join(__dirname, 'test-temp-src-1');
  const clear = await generatorTempDir(__dirname, testDir);

  const rsbuild = await createRsbuild({
    cwd: __dirname,
    config: {
      plugins: [
        pluginSass({
          include: [/a\.module/],
        }),
        pluginSass({
          include: [/b\.module/],
        }),
        pluginLess({
          include: [/c\.module/],
        }),
        pluginLess({
          include: [/d\.module/],
        }),
        pluginTypedCSSModules(),
      ],
      source: {
        entry: { index: resolve(testDir, 'index.js') },
      },
    },
  });

  await rsbuild.build();

  expect(fs.existsSync(join(testDir, './a.module.scss.d.ts'))).toBeTruthy();
  expect(fs.existsSync(join(testDir, './b.module.scss.d.ts'))).toBeTruthy();
  expect(fs.existsSync(join(testDir, './c.module.less.d.ts'))).toBeTruthy();
  expect(fs.existsSync(join(testDir, './d.module.less.d.ts'))).toBeTruthy();

  const aContent = fs.readFileSync(join(testDir, './a.module.scss.d.ts'), {
    encoding: 'utf-8',
  });
  expect(aContent).toEqual(`// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  a: string;
}
declare const cssExports: CssExports;
export default cssExports;
`);

  const bContent = fs.readFileSync(join(testDir, './b.module.scss.d.ts'), {
    encoding: 'utf-8',
  });
  expect(bContent).toEqual(`// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  b: string;
}
declare const cssExports: CssExports;
export default cssExports;
`);

  const cContent = fs.readFileSync(join(testDir, './c.module.less.d.ts'), {
    encoding: 'utf-8',
  });
  expect(cContent).toEqual(`// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  c: string;
}
declare const cssExports: CssExports;
export default cssExports;
`);

  const dContent = fs.readFileSync(join(testDir, './d.module.less.d.ts'), {
    encoding: 'utf-8',
  });
  expect(dContent).toEqual(`// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  d: string;
}
declare const cssExports: CssExports;
export default cssExports;
`);

  await clear();
});
