import fs from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { expect, test } from '@playwright/test';
import { createRsbuild } from '@rsbuild/core';
import { pluginSass } from '@rsbuild/plugin-sass';
import { pluginTypedCSSModules } from '../../dist';

const __dirname = dirname(fileURLToPath(import.meta.url));
const fixtures = __dirname;

const generatorTempDir = async (testDir: string) => {
  fs.rmSync(testDir, { recursive: true, force: true });
  await fs.promises.cp(join(fixtures, 'src'), testDir, { recursive: true });

  return () => fs.promises.rm(testDir, { force: true, recursive: true });
};

test('generator TS declaration with loose typing', async () => {
  const testDir = join(fixtures, 'test-temp-src-1');
  const clear = await generatorTempDir(testDir);

  const rsbuild = await createRsbuild({
    cwd: __dirname,
    rsbuildConfig: {
      plugins: [
        pluginSass(),
        pluginTypedCSSModules({
          looseTyping: true,
        }),
      ],
      source: {
        entry: { index: resolve(testDir, 'index.js') },
      },
    },
  });

  await rsbuild.build();

  expect(fs.existsSync(join(testDir, './a.module.scss.d.ts'))).toBeTruthy();
  const aContent = fs.readFileSync(join(testDir, './a.module.scss.d.ts'), {
    encoding: 'utf-8',
  });
  expect(aContent).toEqual(`// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  a: string;
  [key: string]: string;
}
declare const cssExports: CssExports;
export default cssExports;
`);

  await clear();
});
