import fs from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { expect, test } from '@playwright/test';
import { createRsbuild } from '@rsbuild/core';
import { pluginLess } from '@rsbuild/plugin-less';
import { pluginSass } from '@rsbuild/plugin-sass';
import { pluginStylus } from '@rsbuild/plugin-stylus';
import { pluginTypedCSSModules } from '../../dist';

const __dirname = dirname(fileURLToPath(import.meta.url));

const generatorTempDir = async (testDir: string) => {
  fs.rmSync(testDir, { recursive: true, force: true });
  await fs.promises.cp(join(__dirname, 'src'), testDir, { recursive: true });

  return () => fs.promises.rm(testDir, { force: true, recursive: true });
};

test('generator TS declaration for cssModules.auto true', async () => {
  const testDir = join(__dirname, 'test-temp-src-1');
  const clear = await generatorTempDir(testDir);

  const rsbuild = await createRsbuild({
    cwd: __dirname,
    rsbuildConfig: {
      plugins: [
        pluginLess(),
        pluginSass(),
        pluginStylus(),
        pluginTypedCSSModules(),
      ],
      source: {
        entry: { index: resolve(testDir, 'index.js') },
      },
    },
  });

  await rsbuild.build();

  expect(fs.existsSync(join(testDir, './a.css.d.ts'))).toBeFalsy();
  expect(fs.existsSync(join(testDir, './b.module.scss.d.ts'))).toBeTruthy();
  expect(fs.existsSync(join(testDir, './c.module.less.d.ts'))).toBeTruthy();
  expect(fs.existsSync(join(testDir, './d.global.less.d.ts'))).toBeFalsy();
  expect(fs.existsSync(join(testDir, './e.module.styl.d.ts'))).toBeTruthy();

  const bContent = fs.readFileSync(join(testDir, './b.module.scss.d.ts'), {
    encoding: 'utf-8',
  });

  expect(bContent).toEqual(`// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  _underline: string;
  btn: string;
  default: string;
  primary: string;
  'the-b-class': string;
  theBClass: string;
  underline: string;
}
declare const cssExports: CssExports;
export default cssExports;
`);

  const cContent = fs.readFileSync(join(testDir, './c.module.less.d.ts'), {
    encoding: 'utf-8',
  });

  expect(cContent).toEqual(`// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'the-c-class': string;
  theCClass: string;
}
declare const cssExports: CssExports;
export default cssExports;
`);

  await clear();
});

test('generator TS declaration for cssModules.auto function', async () => {
  const testDir = join(__dirname, 'test-temp-src-2');
  const clear = await generatorTempDir(testDir);

  const rsbuild = await createRsbuild({
    cwd: __dirname,
    rsbuildConfig: {
      plugins: [
        pluginLess(),
        pluginSass(),
        pluginStylus(),
        pluginTypedCSSModules(),
      ],
      source: {
        entry: { index: resolve(testDir, 'index.js') },
      },
      output: {
        cssModules: {
          auto: (path) => {
            return path.endsWith('.scss');
          },
        },
      },
    },
  });

  await rsbuild.build();

  expect(fs.existsSync(join(testDir, './a.css.d.ts'))).toBeFalsy();
  expect(fs.existsSync(join(testDir, './b.module.scss.d.ts'))).toBeTruthy();
  expect(fs.existsSync(join(testDir, './c.module.less.d.ts'))).toBeFalsy();
  expect(fs.existsSync(join(testDir, './d.global.less.d.ts'))).toBeFalsy();

  await clear();
});

test('generator TS declaration for cssModules.auto Regexp', async () => {
  const testDir = join(__dirname, 'test-temp-src-3');
  const clear = await generatorTempDir(testDir);

  const rsbuild = await createRsbuild({
    cwd: __dirname,
    rsbuildConfig: {
      plugins: [
        pluginLess(),
        pluginSass(),
        pluginStylus(),
        pluginTypedCSSModules(),
      ],
      source: {
        entry: { index: resolve(testDir, 'index.js') },
      },
      output: {
        cssModules: {
          auto: /\.module\./i,
        },
      },
    },
  });

  await rsbuild.build();

  expect(fs.existsSync(join(testDir, './a.css.d.ts'))).toBeFalsy();
  expect(fs.existsSync(join(testDir, './b.module.scss.d.ts'))).toBeTruthy();
  expect(fs.existsSync(join(testDir, './c.module.less.d.ts'))).toBeTruthy();
  expect(fs.existsSync(join(testDir, './d.global.less.d.ts'))).toBeFalsy();

  await clear();
});

test('generator TS declaration for `asIs` convention', async () => {
  const testDir = join(__dirname, 'test-temp-src-4');
  const clear = await generatorTempDir(testDir);

  const rsbuild = await createRsbuild({
    cwd: __dirname,
    rsbuildConfig: {
      plugins: [
        pluginLess(),
        pluginSass(),
        pluginStylus(),
        pluginTypedCSSModules(),
      ],
      source: {
        entry: { index: resolve(testDir, 'index.js') },
      },
      output: {
        cssModules: {
          exportLocalsConvention: 'asIs',
        },
      },
    },
  });

  await rsbuild.build();

  expect(fs.existsSync(join(testDir, './b.module.scss.d.ts'))).toBeTruthy();
  expect(fs.existsSync(join(testDir, './c.module.less.d.ts'))).toBeTruthy();

  const bContent = fs.readFileSync(join(testDir, './b.module.scss.d.ts'), {
    encoding: 'utf-8',
  });
  const cContent = fs.readFileSync(join(testDir, './c.module.less.d.ts'), {
    encoding: 'utf-8',
  });

  expect(bContent).toEqual(`// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  _underline: string;
  btn: string;
  default: string;
  primary: string;
  'the-b-class': string;
}
declare const cssExports: CssExports;
export default cssExports;
`);

  expect(cContent).toEqual(`// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'the-c-class': string;
}
declare const cssExports: CssExports;
export default cssExports;
`);

  await clear();
});
